server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Check if the file or directory exists, else fallback to index.html
        try_files $uri $uri/ /index.html;
    }

    # Optional: Cache static assets (JS, CSS, Images)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}